apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com # EBS CSI driver
parameters:
  type: gp3 # Change to gp2 if gp3 is unavailable
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

